### ISSUE TITLE
Support semver increment 

### ISSUE THREAD

**Issue by rkesters** [absolute-version/absolute-version-js#5] opened 2023-06-13 03:13 UTC
The docs state:

If the most recent commit is not tagged, then it will output a prerelease version, for example.

1.2.3-master+26.6fe275b

* 1.2.3: The most recent tagged version that this version is based on
* master: The current branch for this version
* 26: The number of commits on this branch (master) since the last version (1.2.3)
* 6fe275b: The commit hash for this version, useful for disambiguation

This is not what I expected, `1.2.3-master+26.6fe275b` is a pre-release of v1.2.3. But in the stated case v1.2.3 has already been released. Hence I expected the output to vary based on the conventional commits, that is 

* if we only had `feat` commits then the version would be 1.3.0-master+26.6fe275b
* if we only had `fix` commits then the version would be 1.2.4-master+26.6fe275b
* if we had `feat` and `fix` commits then the version would be 1.3.0-master+26.6fe275b

Thoughts?

**Comment by TimothyJones** [comment] 2023-06-13 05:19
> 1.2.3-master+26.6fe275b is a pre-release of v1.2.3. But

I believe this is convention (in some ecosystems, I'm not actually sure which ones), and not part of the spec. As I understand the [semver spec](https://semver.org/#spec-item-9) only says:

> A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.--.

The reason I (and others) mark non-released pre-releases this way is that is that they can never be selected as higher than the published version in the case that they do get published. I would feel differently if you were publishing each pre-release, but if you're publishing each absolute-version, then why not just make each one a first-class releases, say with a `-beta` pre-release tag? 

What's the use case for having the prerelease tag based on the next version?

> Hence I expected the output to vary based on the conventional commits

Why did you expect this? I don't see this suggestion in the documentation, but absolute-version has no opinions on how you do your commits (if I accidentally implied there was one in the documentation, I apologise - please let me know).

The reliance on git tag was because tags happen to be how most people were marking versions for the use case this was designed for. I originally planned to add other hooks for finding out the current version - eg, from package.json, or perhaps passed in programmatically (though it gets complicated quickly as you want to be able to find out how many commits ago that version was made - even parsing git-blame doesn't get you a certain answer).

If we added a programmatic method where you told it the version number and the commit distance, then it would be possible to have the behaviour you want. Note that would deviate from the [absolute-version spec](https://github.com/absolute-version/specification) - but that might not matter to you.

**Comment by rkesters** [comment] 2023-06-13 15:41
More context, my project use both Typescript and Rust. Rust complains in the following case:

1. cargo set-version 0.21.1 (works)
2. cargo set-version 0.21.1-rc.0 (fails with error message ` Cannot downgrade`)

Hence rust see this as a step backward.

**Comment by TimothyJones** [comment] 2023-06-13 22:06
I can’t easily see what has changed, sorry.

Why are the version numbers generated by absolute-version ending up in your package manager? I think perhaps this tool might not be the right tool for your use case

**Comment by TimothyJones** [comment] 2023-06-13 22:23
I don't use rust, so I tried to look up that command to see if you have any options (seems odd that you can't set a semver-earlier version). But it's not [documented as part of Cargo](https://doc.rust-lang.org/cargo/commands/index.html). Is it perhaps provided by this [third party extension](https://github.com/killercup/cargo-edit)? I don't see anything in the documentation that says that it restricts only semver increases, which is odd.

> This is not what I expected

I think the behaviour of absolute-version is clearly documented, so I'm not sure why you're expecting something else. Please let me know which parts of the documentation are misleading if this is not the case.

You you mean that this behaviour doesn't work for your use case - I can perhaps help if you tell me more about what you're trying to use absolute-version for.

**Comment by rkesters** [comment] 2023-06-14 03:08
I'm expecting a valid semver,  if we look at the precedence section of the semver spec, we see.


3. When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version:

Example: 1.0.0-alpha < 1.0.0

Hence, this package generates a version that includes changes after version 1.0.0 but labels it as if it came before version 1.0.0

Things are pushed to local repository so that integration testing can be done.

**Comment by TimothyJones** [comment] 2023-06-14 03:25
It is a valid semver, the statement there isn’t violated.

I’ll have a think about this use case. I think you want a different tool, though.

**Comment by TimothyJones** [comment] 2023-06-14 04:35
> Hence, this package generates a version that includes changes after version 1.0.0 but labels it as if it came before version 1.0.0

No, it labels it as lower precedence than version 1.0.0. Which it is; we never want these versions to be selected by a package manager if a released version is available.

**Comment by TimothyJones** [comment] 2024-06-22 06:53
I'll close this for now, as the current behaviour is intended and spec compliant. 

Please do reopen if you feel this is in error, or we should bring this feature request in.

**Closed by TimothyJones** 2024-06-22 06:53 UTC
